info:
#  name: "lucien"
  school:
    schoolName: "xupt"
    departmentName: "CS"
  age: 21
  isMarried: false

db:
  default:
    driver: "mysql"
    host: "127.0.0.1"
    port: 3306
    database: "lucien_test_db"
    username: "root"
    password: "password"